CREATE OR REPLACE STORAGE integration s3_int
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::748152359619:role/Retail_Role_001' 
STORAGE_ALLOWED_LOCATIONS =('s3://retailraw01/');

desc integration s3_int;


CREATE OR REPLACE STAGE RETAIL
URL ='s3://retailraw01/'
file_format = FORMAT_RETAIL_TABLES
storage_integration = s3_int;

LIST @RETAIL;

SHOW STAGES;


LIST @RETAIL;



--CREATING SNOWPIPE THAT RECOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO EXISTING TABLE
--The AUTO_INGEST=true parameter specifies to read 
--- event notifications sent from an S3 bucket to an SQS queue when new data is ready to load.

SHOW TABLES;


CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_COUPON AUTO_INGEST = TRUE AS
COPY INTO "RETAILS"."PUBLIC"."COUPON_RAW" --yourdatabase -- your schema ---your table
FROM '@RETAIL/COUPON/' --s3 bucket subfolde4r name
file_format = FORMAT_RETAIL_TABLES;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_COUPON_REDMPT AUTO_INGEST = TRUE AS
COPY INTO "RETAILS"."PUBLIC"."COUPON_REDEMPT_RAW" --yourdatabase -- your schema ---your table
FROM '@RETAIL/COUPON_REDMPT/' --STAGE/STAGE_TABLE
file_format = FORMAT_RETAIL_TABLES;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_CAMPAIGN_DESC AUTO_INGEST = TRUE AS
COPY INTO "RETAILS"."PUBLIC"."CAMPAIGN_DESC_RAW" --yourdatabase -- your schema ---your table
FROM '@RETAIL/CAMPAIGN_DESC/' -- @STAGE_NAME/TABLENAME AS IN STAGE
file_format = FORMAT_RETAIL_TABLES;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_CAMPAIGN AUTO_INGEST = TRUE AS
COPY INTO "RETAILS"."PUBLIC"."CAMPAIGN_RAW" --yourdatabase -- your schema ---your table
FROM '@RETAIL/CAMPAIGN/' -- @STAGE_NAME/TABLENAME AS IN STAGE
file_format = FORMAT_RETAIL_TABLES;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_DEMOGRAPHIC AUTO_INGEST = TRUE AS
COPY INTO "RETAILS"."PUBLIC"."DEMOGRAPHIC_RAW"
FROM '@RETAIL/DEMOGRAPHIC/'
file_format = FORMAT_RETAIL_TABLES;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_PRODUCT AUTO_INGEST = TRUE AS
COPY INTO "RETAILS"."PUBLIC"."PRODUCT_RAW"
FROM '@RETAIL/PRODUCT/'
file_format = FORMAT_RETAIL_TABLES;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_TRANSACTION AUTO_INGEST = TRUE AS
COPY INTO "RETAILS"."PUBLIC"."TRANSACTION_RAW"
FROM '@RETAIL/TRANSACTION/'
file_format = FORMAT_RETAIL_TABLES;


SHOW PIPES;



SELECT COUNT(*) FROM DEMOGRAPHIC_RAW;
SELECT COUNT(*) FROM CAMPAIGN_DESC_RAW;
SELECT COUNT(*) FROM CAMPAIGN_RAW;
SELECT COUNT(*) FROM PRODUCT_RAW;
SELECT COUNT(*) FROM COUPON_RAW;
SELECT COUNT(*) FROM COUPON_REDEMPT_RAW;
SELECT COUNT(*) FROM TRANSACTION_RAW;

----------------------------------------------------------PIPEREFRESH-----------------------------------------------------------------

ALTER PIPE RETAIL_SNOWPIPE_DEMOGRAPHIC refresh;
ALTER PIPE  RETAIL_SNOWPIPE_CAMPAIGN_DESC refresh;
ALTER PIPE  RETAIL_SNOWPIPE_CAMPAIGN refresh;
ALTER PIPE  RETAIL_SNOWPIPE_PRODUCT refresh;
ALTER PIPE  RETAIL_SNOWPIPE_COUPON refresh;
ALTER PIPE  RETAIL_SNOWPIPE_COUPON_REDMPT refresh;
ALTER PIPE  RETAIL_SNOWPIPE_TRANSACTION refresh;



SELECT * FROM demographic_RAW;
SELECT * FROM CAMPAIGN_DESC_RAW;
SELECT * FROM CAMPAIGN_RAW;
SELECT * FROM PRODUCT_RAW;
SELECT * FROM COUPON_RAW;
SELECT * FROM COUPON_REDEMPT_RAW;
SELECT * FROM TRANSACTION_RAW;